const state={games:[],consoles:[],queue:[],selected:new Set(),console:null,filter:'all',search:'',sort:'title',ps2Games:[],usb:[],ps2Queue:[],ps2Selected:new Set(),ps2USB:'',ps2Filter:'all',ps2Search:'',ps2Sort:'title',ps4Games:[],ps4Consoles:[],ps4Queue:[],ps4Selected:new Set(),ps4Console:null,ps4Filter:'all',ps4Search:'',ps4Sort:'title',ps4RPIPort:12800,ps5Games:[],ps5Consoles:[],ps5Queue:[],ps5Selected:new Set(),ps5Console:null,ps5Filter:'all',ps5Search:'',ps5Sort:'title'};
const $=id=>document.getElementById(id);
const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options});if(!response.ok){let body={};try{body=await response.json()}catch{}throw new Error(body.error||`Request failed (${response.status})`)}return response.status===204?null:response.json()};
const asArray=value=>Array.isArray(value)?value:[];
const formatBytes=n=>{if(!n)return'0 B';const units=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return`${n.toFixed(i<2?0:1)} ${units[i]}`};
const formatTime=s=>{if(!s)return'—';const m=Math.floor(s/60);return m?`${m}m ${s%60}s`:`${s}s`};
const viewPaths={dashboard:'/dashboard',ps2games:'/ps2-games',ps2usb:'/ps2-usb',ps2queue:'/ps2-queue',games:'/ps3-games',consoles:'/ps3-consoles',scan:'/ps3-scan',queue:'/ps3-queue',ps4games:'/ps4-games',ps4consoles:'/ps4-consoles',ps4scan:'/ps4-scan',ps4queue:'/ps4-queue',ps5games:'/ps5-games',ps5consoles:'/ps5-consoles',ps5scan:'/ps5-scan',ps5queue:'/ps5-queue'},pathViews=Object.fromEntries(Object.entries(viewPaths).map(([view,path])=>[path,view]));
function showView(name,push=true){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('.nav').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$('pageTitle').textContent={dashboard:'Dashboard',ps2games:'PS2 Game Library',ps2usb:'PS2 USB Devices',ps2queue:'PS2 Transfer Queue',games:'PS3 Game Library',consoles:'PS3 Consoles',scan:'Network Scan',queue:'PS3 Transfer Queue',ps4games:'PS4 Package Library',ps4consoles:'PS4 Consoles',ps4scan:'PS4 Network Scan',ps4queue:'PS4 Install Queue',ps5games:'PS5 Game Library',ps5consoles:'PS5 Consoles',ps5scan:'PS5 Network Scan',ps5queue:'PS5 Transfer Queue'}[name];$('eyebrow').textContent={dashboard:'PLATFORM OVERVIEW',ps2games:'LOCAL ISO COLLECTION',ps2usb:'OPL USB TARGETS',ps2queue:'OPL / USB ACTIVITY',games:'LOCAL PS3 COLLECTION',consoles:'CONNECTED HARDWARE',scan:'DISCOVERY',queue:'FTP ACTIVITY',ps4games:'LOCAL PKG COLLECTION',ps4consoles:'REMOTE PACKAGE INSTALLER',ps4scan:'API 12800 DISCOVERY',ps4queue:'REMOTE PKG ACTIVITY',ps5games:'SHADOWMOUNTPLUS COLLECTION',ps5consoles:'ETAHEN HARDWARE',ps5scan:'FTP 2121 DISCOVERY',ps5queue:'SHADOWMOUNTPLUS FTP ACTIVITY'}[name];if(push&&viewPaths[name]&&location.pathname!==viewPaths[name])history.pushState({view:name},'',viewPaths[name])}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();showView(button.dataset.view)}));window.addEventListener('popstate',()=>showView(pathViews[location.pathname]||'dashboard',false));showView(pathViews[location.pathname]||'dashboard',false);
function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('toasts').append(el);setTimeout(()=>el.remove(),4500)}
function bindGameCards(selector,selectedGames,render){document.querySelectorAll(selector).forEach(card=>{const toggle=()=>{const id=card.dataset.game;selectedGames.has(id)?selectedGames.delete(id):selectedGames.add(id);render()};card.onclick=toggle;card.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle()}}})}
async function loadPS2Games(){try{state.ps2Games=asArray(await api('/api/ps2/games'));$('statPS2Games').textContent=state.ps2Games.length;renderPS2Games()}catch(error){$('ps2GameGrid').innerHTML=`<div class="empty">${escapeHTML(error.message)}</div>`}}
async function loadPS2CoverStatus(){const el=$('ps2CoverStatus');try{const status=await api('/api/ps2/covers/status'),path=escapeHTML(status.cache_dir||'covers/');if(!status.enabled){el.innerHTML=`<strong>Local cover cache:</strong> downloads are disabled. Existing images are read from <code>${path}</code>.`;return}if(status.error){el.innerHTML=`<strong>Cover cache unavailable:</strong> <code>${path}</code><br><span class="status failed">${escapeHTML(status.error)}</span>`;return}el.innerHTML=`<strong>Local cover cache ready:</strong> <code>${path}</code> inside the container · ${status.images||0} cached image${status.images===1?'':'s'}. Missing known serials are downloaded once and then served offline.`}catch(error){el.innerHTML=`<strong>Cover cache status failed:</strong> <span class="status failed">${escapeHTML(error.message)}</span>`}}
function displayedPS2Games(){const q=state.ps2Search.toLowerCase();return state.ps2Games.filter(g=>(!q||g.title.toLowerCase().includes(q)||(g.id||'').toLowerCase().includes(q))&&(state.ps2Filter==='all'||(state.ps2Filter==='installed')===!!g.usb_installed)).sort((a,b)=>state.ps2Sort==='size'?b.size-a.size:a.title.localeCompare(b.title))}
function renderPS2Games(){const list=displayedPS2Games();$('ps2GameGrid').classList.toggle('empty',!list.length);$('ps2GameGrid').innerHTML=list.length?list.map(game=>{const selected=state.ps2Selected.has(game.public_id),job=[...state.ps2Queue].reverse().find(j=>j.game.public_id===game.public_id),status=job?job.state:(game.usb_installed?'INSTALLED':game.opl_ready?'OPL_READY':'ID_UNKNOWN');return`<article class="game-card ps2-game-card ${selected?'selected':''}" role="button" tabindex="0" aria-pressed="${selected}" aria-label="${attr(`${selected?'Deselect':'Select'} ${game.title}`)}" data-game="${attr(game.public_id)}"><div class="cover">${game.cover_url?`<img loading="lazy" src="${attr(game.cover_url)}" alt="">`:`<span class="placeholder">PS2</span>`}</div><div class="game-body"><h3 class="game-title" title="${attr(game.title)}">${escapeHTML(game.title)}</h3><div class="game-meta"><span>${escapeHTML(game.id||'unknown')}</span><span>${formatBytes(game.size)}</span></div><div class="game-meta"><span>${escapeHTML(game.iso_filename)}</span></div><span class="status ${status.toLowerCase()}">${labelState(status)}</span></div></article>`}).join(''):'No PS2 games match this view.';bindGameCards('.ps2-game-card',state.ps2Selected,renderPS2Games);renderPS2Selection()}
function renderPS2Selection(){let size=0;state.ps2Games.forEach(g=>{if(state.ps2Selected.has(g.public_id))size+=g.size});$('ps2SelectionCount').textContent=`${state.ps2Selected.size} game${state.ps2Selected.size===1?'':'s'} selected`;$('ps2SelectionSize').textContent=formatBytes(size);$('ps2InstallSelected').disabled=!state.ps2Selected.size||!state.ps2USB}
$('ps2Search').oninput=e=>{state.ps2Search=e.target.value;renderPS2Games()};$('ps2Filter').onchange=e=>{state.ps2Filter=e.target.value;renderPS2Games()};$('ps2Sort').onchange=e=>{state.ps2Sort=e.target.value;renderPS2Games()};$('ps2SelectAll').onclick=()=>{displayedPS2Games().forEach(g=>state.ps2Selected.add(g.public_id));renderPS2Games()};$('ps2SelectMissing').onclick=()=>{state.ps2Selected.clear();state.ps2Games.filter(g=>!g.usb_installed).forEach(g=>state.ps2Selected.add(g.public_id));renderPS2Games()};$('ps2SelectNone').onclick=()=>{state.ps2Selected.clear();renderPS2Games()};
async function loadUSB(){try{const discovery=await api('/api/ps2/usb/status');state.usb=discovery.targets||[];if(state.ps2USB&&!state.usb.some(target=>target.id===state.ps2USB)){state.ps2USB='';state.ps2Selected.clear();toast('The selected PS2 USB target is no longer available','error')}$('statUSB').textContent=state.usb.length;const issues=(discovery.issues||[]).map(issue=>`${issue.path}: ${issue.reason}`).join(' · ');$('usbDiscoveryStatus').innerHTML=`Root: <strong>${escapeHTML(discovery.root)}</strong> · Mode: ${escapeHTML(discovery.mode||'unknown')} · ${state.usb.length} target${state.usb.length===1?'':'s'}${issues?`<br><span class="status failed">${escapeHTML(issues)}</span>`:''}`;const select=$('ps2Target');select.innerHTML='<option value="">Select USB target…</option>'+state.usb.map(u=>`<option value="${attr(u.id)}" ${u.id===state.ps2USB?'selected':''}>${escapeHTML(u.name)} — ${formatBytes(u.free_bytes)} free</option>`).join('');renderUSB();renderPS2Selection()}catch(error){$('usbDiscoveryStatus').textContent=error.message;toast(error.message,'error')}}
function renderUSB(){const el=$('ps2USBGrid');el.classList.toggle('empty',!state.usb.length);el.innerHTML=state.usb.length?state.usb.map(u=>{const fatClass=u.fat32_status==='COMPATIBLE'?'installed':u.fat32_status==='INCOMPATIBLE'?'failed':'id_unknown';return`<article class="console-card ${state.ps2USB===u.id?'selected':''}"><p class="eyebrow">PLAYSTATION 2 / OPL</p><h3>${escapeHTML(u.name)}</h3><p>Mount: ${escapeHTML(u.mount_path)}</p><p>Filesystem: <strong>${escapeHTML(u.filesystem||'unknown')}</strong></p><p><span class="status ${fatClass}">FAT32: ${escapeHTML(u.fat32_status||'UNKNOWN')}</span></p><p class="compat-detail">${escapeHTML(u.compatibility_note||'Verify FAT32 on the Docker host.')}</p><p><span class="${u.read_only?'status failed':'online'}">● ${u.read_only?'Read only':'Available'}</span> · ${formatBytes(u.free_bytes)} free</p><p>OPL: ${u.opl_ready?'Compatible layout detected':'Not initialized'}</p><div class="console-actions"><button class="button ${state.ps2USB===u.id?'ghost':'primary'} select-usb" data-id="${attr(u.id)}">${state.ps2USB===u.id?'Selected':'Use '+escapeHTML(u.name)}</button><button class="button ghost prepare-usb" data-id="${attr(u.id)}" ${u.read_only?'disabled':''}>Initialize OPL Layout</button></div></article>`}).join(''):'No PS2 USB devices detected.<br>Make sure the USB filesystem is mounted inside the container.';document.querySelectorAll('.select-usb').forEach(button=>button.onclick=()=>selectUSB(button.dataset.id));document.querySelectorAll('.prepare-usb').forEach(button=>button.onclick=()=>prepareUSB(button))}
async function prepareUSB(button){const original=button.textContent;button.disabled=true;button.textContent='Initializing…';try{const target=await api(`/api/ps2/usb/${encodeURIComponent(button.dataset.id)}/prepare`,{method:'POST'});toast(`${target.name} OPL layout initialized`,'success');await loadUSB()}catch(error){toast(error.message,'error')}finally{button.disabled=false;button.textContent=original}}
async function selectUSB(id){state.ps2USB=id;$('ps2Target').value=id;renderUSB();renderPS2Selection();try{const compared=asArray(await api(`/api/ps2/compare/${encodeURIComponent(id)}`));state.ps2Games=compared.map(item=>({...item.game,usb_installed:item.installed}));renderPS2Games();toast(`${id} selected for PS2 installs`,'success')}catch(error){toast(error.message,'error')}}
$('ps2Target').onchange=e=>e.target.value?selectUSB(e.target.value):(state.ps2USB='',renderPS2Selection());$('refreshUSB').onclick=loadUSB;
$('ps2InstallSelected').onclick=async()=>{try{const count=state.ps2Selected.size;await api('/api/ps2/queue',{method:'POST',body:JSON.stringify({usb_id:state.ps2USB,game_ids:[...state.ps2Selected]})});state.ps2Selected.clear();await loadPS2Queue();renderPS2Games();toast(`${count} PS2 games added to the PS2 queue`,'success');showView('ps2queue')}catch(error){toast(error.message,'error')}};
async function loadPS2Queue(){try{state.ps2Queue=asArray(await api('/api/ps2/queue'));renderPS2Queue();renderPS2Games()}catch(error){toast(error.message,'error')}}
function renderPS2Queue(){const active=state.ps2Queue.filter(j=>!['COMPLETED','FAILED','CANCELLED'].includes(j.state));$('ps2QueueBadge').textContent=active.length;$('statPS2Queue').textContent=active.length;$('statPS2Active').textContent=state.ps2Queue.filter(j=>['PREPARING','CONVERTING','WRITING','VERIFYING'].includes(j.state)).length;const list=$('ps2QueueList');list.classList.toggle('empty',!state.ps2Queue.length);list.innerHTML=state.ps2Queue.length?state.ps2Queue.slice().reverse().map(item=>{const p=item.progress||{};return`<article class="queue-item"><div class="queue-top"><div><p class="eyebrow">${labelState(item.state)} · ${escapeHTML(item.usb_id)}</p><h3>${escapeHTML(item.game.title)}</h3></div><strong>${(p.percentage||0).toFixed(1)}%</strong></div><div class="progress"><i style="width:${Math.min(100,p.percentage||0)}%"></i></div><div class="queue-details"><span>${formatBytes(p.bytes)} / ${formatBytes(p.total)}</span><span>${formatBytes(p.speed)}/s · ETA ${formatTime(p.eta_seconds)}</span><span>${escapeHTML(p.current_file||item.state)}</span></div>${item.error?`<p class="status failed">${escapeHTML(item.error)}</p>`:''}<div class="queue-actions">${!['COMPLETED','FAILED','CANCELLED'].includes(item.state)?`<button class="button ghost ps2-queue-action" data-action="cancel" data-id="${attr(item.id)}">Cancel</button>`:''}${['FAILED','CANCELLED','PAUSED'].includes(item.state)?`<button class="button ghost ps2-queue-action" data-action="retry" data-id="${attr(item.id)}">Retry</button>`:''}</div></article>`}).join(''):'The PS2 queue is empty.';document.querySelectorAll('.ps2-queue-action').forEach(b=>b.onclick=async()=>{try{await api(`/api/ps2/queue/${encodeURIComponent(b.dataset.id)}/${b.dataset.action}`,{method:'POST'});await loadPS2Queue()}catch(error){toast(error.message,'error')}})}
async function loadGames(){try{state.games=asArray(await api('/api/local-games'));$('statGames').textContent=state.games.length;renderGames()}catch(error){$('gameGrid').innerHTML=`<div class="empty">${escapeHTML(error.message)}</div>`;toast(error.message,'error')}}
function displayedGames(){let games=state.games.filter(g=>{const q=state.search.toLowerCase();const matches=!q||g.title.toLowerCase().includes(q)||(g.id||'').toLowerCase().includes(q);if(!matches)return false;if(state.filter==='installed')return g.installed;if(state.filter==='missing')return !g.installed;if(state.filter==='queued')return state.queue.some(t=>t.game.id===g.id&&!['COMPLETED','FAILED','CANCELLED'].includes(t.state));return true});return games.sort((a,b)=>state.sort==='size'?b.size-a.size:a.title.localeCompare(b.title))}
function renderGames(){const list=displayedGames();$('gameGrid').classList.toggle('empty',!list.length);$('gameGrid').innerHTML=list.length?list.map(game=>{const id=publicID(game),selected=state.selected.has(id),status=queueState(game);return`<article class="game-card ps3-game-card ${selected?'selected':''}" role="button" tabindex="0" aria-pressed="${selected}" aria-label="${attr(`${selected?'Deselect':'Select'} ${game.title}`)}" data-game="${attr(id)}"><div class="cover">${game.icon_url?`<img loading="lazy" src="${attr(game.icon_url)}" alt="">`:`<span class="placeholder">PS3</span>`}</div><div class="game-body"><h3 class="game-title" title="${attr(game.title)}">${escapeHTML(game.title)}</h3><div class="game-meta"><span>${escapeHTML(game.id||'ID unknown')}</span><span>${formatBytes(game.size)}</span></div><span class="status ${status.toLowerCase()}">${labelState(status)}</span></div></article>`}).join(''):'No games match this view.';bindGameCards('.ps3-game-card',state.selected,renderGames);renderSelection()}
function publicID(game){return game.id||game.title.toLowerCase().replace(/[^a-z0-9]/g,'')}
function queueState(game){const item=[...state.queue].reverse().find(t=>publicID(t.game)===publicID(game));if(item)return item.state==='WAITING'?'QUEUED':item.state;return game.installed?'INSTALLED':'NOT_INSTALLED'}
function labelState(value){return({NOT_INSTALLED:'+ NOT INSTALLED',INSTALLED:'✓ INSTALLED',OPL_READY:'✓ OPL READY',ID_UNKNOWN:'! ID UNKNOWN',QUEUED:'◷ QUEUED',WAITING:'◷ WAITING',STARTING:'→ STARTING',PREPARING:'→ PREPARING',VALIDATING:'→ VALIDATING',SERVING:'↗ SERVING PKG',REQUESTING_INSTALL:'→ STARTING INSTALL',DOWNLOADING:'↓ PS4 DOWNLOADING',CONVERTING:'↻ CONVERTING',WRITING:'↥ WRITING',TRANSFERRING:'↥ TRANSFERRING',VERIFYING:'◇ VERIFYING',COMPLETED:'✓ COMPLETED',FAILED:'! FAILED',CANCELLED:'× CANCELLED',PAUSED:'Ⅱ PAUSED'})[value]||value}
function renderSelection(){let size=0;state.games.forEach(g=>{if(state.selected.has(publicID(g)))size+=g.size});$('selectionCount').textContent=`${state.selected.size} game${state.selected.size===1?'':'s'} selected`;$('selectionSize').textContent=formatBytes(size);$('installSelected').disabled=!state.selected.size||!state.console}
$('gameSearch').addEventListener('input',e=>{state.search=e.target.value;renderGames()});$('gameFilter').addEventListener('change',e=>{state.filter=e.target.value;renderGames()});$('gameSort').addEventListener('change',e=>{state.sort=e.target.value;renderGames()});
$('selectAll').onclick=()=>{displayedGames().forEach(g=>state.selected.add(publicID(g)));renderGames()};$('selectMissing').onclick=()=>{state.selected.clear();state.games.filter(g=>!g.installed).forEach(g=>state.selected.add(publicID(g)));renderGames()};$('selectNone').onclick=()=>{state.selected.clear();renderGames()};
$('installSelected').onclick=async()=>{try{await api('/api/queue',{method:'POST',body:JSON.stringify({console_id:state.console,game_ids:[...state.selected]})});toast(`${state.selected.size} games added to the queue`,'success');state.selected.clear();await loadQueue();renderGames();showView('queue')}catch(error){toast(error.message,'error')}};
async function loadConsoles(){state.consoles=asArray(await api('/api/consoles'));$('statConsoles').textContent=state.consoles.length;renderConsoles()}
async function showInstalledGames(platform,id){const target=platform==='ps3'?'installedGames':'ps5InstalledGames';const endpoint=platform==='ps3'?`/api/consoles/${encodeURIComponent(id)}/games`:`/api/ps5/consoles/${encodeURIComponent(id)}/games`;const pull=platform==='ps3'?'/api/pull':'/api/ps5/pull';const el=$(target);el.innerHTML='<div class="loading">Loading installed games…</div>';try{const games=asArray(await api(endpoint));el.innerHTML=`<div class="panel-head"><div><p class="eyebrow">${platform.toUpperCase()} · ${id}</p><h3>Installed games (${games.length})</h3></div></div>`+(games.length?`<div class="installed-list">${games.map(g=>`<div class="installed-row"><span><strong>${escapeHTML(g.title)}</strong><small>${escapeHTML(g.id||g.remote_path||'')}</small></span><button class="button ghost pull-game" data-platform="${platform}" data-endpoint="${pull}" data-id="${attr(g.id||g.title)}">Pull to local</button></div>`).join('')}</div>`:'<p>No installed games found.</p>');el.querySelectorAll('.pull-game').forEach(button=>button.onclick=async()=>{button.disabled=true;button.textContent='Queuing…';try{await api(button.dataset.endpoint,{method:'POST',body:JSON.stringify({console_id:id,game_ids:[button.dataset.id]})});toast('Game added to pull queue','success')}catch(error){toast(error.message,'error')}finally{button.disabled=false;button.textContent='Pull to local'}})}catch(error){el.innerHTML=`<p class="status failed">${escapeHTML(error.message)}</p>`}}
function renderConsoles(){const el=$('consoleGrid');el.classList.toggle('empty',!state.consoles.length);el.innerHTML=state.consoles.length?state.consoles.map(c=>`<article class="console-card ${state.console===c.id?'selected':''}"><p class="eyebrow">PLAYSTATION 3</p><h3>${escapeHTML(c.ip)}</h3><p><span class="online">● FTP online</span> · ${c.game_count} games found</p><div class="console-actions"><button class="button ${state.console===c.id?'ghost':'primary'} select-console" data-id="${attr(c.id)}">${state.console===c.id?'Selected':'Select console'}</button><button class="button ghost refresh-console" data-id="${attr(c.id)}">↻ Refresh games</button><button class="button ghost installed-console" data-id="${attr(c.id)}">View installed</button></div></article>`).join(''):'No consoles discovered yet.';document.querySelectorAll('.select-console').forEach(button=>button.onclick=()=>selectConsole(button.dataset.id));document.querySelectorAll('.refresh-console').forEach(button=>button.onclick=()=>refreshConsole(button.dataset.id,button));document.querySelectorAll('.installed-console').forEach(button=>button.onclick=()=>showInstalledGames('ps3',button.dataset.id))}
async function selectConsole(id){state.console=id;renderConsoles();toast(`Loading games from ${id}…`);try{state.games=asArray(await api(`/api/compare/${encodeURIComponent(id)}`));$('statInstalled').textContent=state.games.filter(g=>g.installed).length;renderGames();renderSelection();toast(`${id} selected`,'success');showView('games')}catch(error){toast(error.message,'error')}}
async function refreshConsole(id,button){const original=button?.textContent;if(button){button.disabled=true;button.textContent='Refreshing…'}try{const result=await api(`/api/consoles/${encodeURIComponent(id)}/rescan`,{method:'POST'});await loadConsoles();if(state.console===id){state.games=asArray(result.games);$('statInstalled').textContent=state.games.filter(g=>g.installed).length;renderGames();renderSelection()}toast(`${id} refreshed — ${result.console.game_count} games found`,'success')}catch(error){toast(error.message,'error')}finally{if(button){button.disabled=false;button.textContent=original}}}
$('directForm').onsubmit=async event=>{event.preventDefault();const button=$('directButton');button.disabled=true;button.textContent='Connecting…';try{const console=await api('/api/consoles',{method:'POST',body:JSON.stringify({ip:$('directIP').value})});await loadConsoles();toast(`${console.ip} added`,'success');await selectConsole(console.id)}catch(error){toast(error.message,'error')}finally{button.disabled=false;button.textContent='Add PS3 by IP'}};
$('scanForm').onsubmit=async event=>{event.preventDefault();const button=$('scanButton');button.disabled=true;button.textContent='Scanning…';$('scanResult').textContent='Checking FTP endpoints and PS3 filesystem markers…';try{const found=asArray(await api('/api/scan',{method:'POST',body:JSON.stringify({cidr:$('cidr').value})}));await loadConsoles();$('scanResult').textContent=found.length?`Found ${found.length} PS3 console${found.length===1?'':'s'}.`:'No PS3 console found in that network.';if(found.length===1)await selectConsole(found[0].id)}catch(error){$('scanResult').textContent=error.message;toast(error.message,'error')}finally{button.disabled=false;button.textContent='Scan network'}};
async function loadQueue(){try{state.queue=asArray(await api('/api/queue'));renderQueue();renderGames()}catch(error){toast(error.message,'error')}}
function renderQueue(){const active=state.queue.filter(q=>!['COMPLETED','FAILED','CANCELLED'].includes(q.state));$('queueBadge').textContent=active.length;$('statQueue').textContent=active.length;const list=$('queueList');list.classList.toggle('empty',!state.queue.length);list.innerHTML=state.queue.length?state.queue.slice().reverse().map(item=>`<article class="queue-item"><div class="queue-top"><div><p class="eyebrow">${labelState(item.state)}</p><h3>${escapeHTML(item.game.title)}</h3></div><strong>${(item.percentage||0).toFixed(1)}%</strong></div><div class="progress"><i style="width:${Math.min(100,item.percentage||0)}%"></i></div><div class="queue-details"><span>${formatBytes(item.bytes_transferred)} / ${formatBytes(item.total_bytes)}</span><span>${formatBytes(item.speed)}/s · ETA ${formatTime(item.eta_seconds)}</span><span>${escapeHTML(item.current_file||'Waiting')}</span></div>${item.error?`<p class="status failed">${escapeHTML(item.error)}</p>`:''}<div class="queue-actions">${['WAITING','STARTING','TRANSFERRING','VERIFYING'].includes(item.state)?`<button class="button ghost queue-action" data-action="cancel" data-id="${attr(item.id)}">Cancel</button>`:''}${['FAILED','CANCELLED'].includes(item.state)?`<button class="button ghost queue-action" data-action="retry" data-id="${attr(item.id)}">Retry</button>`:''}</div></article>`).join(''):'Your queue is empty.';$('recentQueue').innerHTML=state.queue.length?state.queue.slice(-4).reverse().map(q=>`<div class="queue-details"><strong>${escapeHTML(q.game.title)}</strong><span class="status ${q.state.toLowerCase()}">${labelState(q.state)}</span></div>`).join(''):'No transfers yet. Choose games to begin.';document.querySelectorAll('.queue-action').forEach(b=>b.onclick=async()=>{try{await api(`/api/queue/${encodeURIComponent(b.dataset.id)}/${b.dataset.action}`,{method:'POST'});await loadQueue()}catch(error){toast(error.message,'error')}})}
$('pauseQueue').onclick=()=>api('/api/queue/pause',{method:'POST'}).then(()=>toast('Queue paused after the active game')).catch(e=>toast(e.message,'error'));
$('resumeQueue').onclick=()=>api('/api/queue/resume',{method:'POST'}).then(()=>toast('Queue resumed','success')).catch(e=>toast(e.message,'error'));
$('clearQueue').onclick=()=>api('/api/queue/completed',{method:'DELETE'}).then(loadQueue).catch(e=>toast(e.message,'error'));
async function loadPS4Games(){try{state.ps4Games=asArray(await api('/api/ps4/games'));$('statPS4Games').textContent=state.ps4Games.length;const status=await api('/api/ps4/content/status');state.ps4RPIPort=status.rpi_port||12800;const listener=status.running?`Package server listening on ${escapeHTML(status.listen)}.`:`<span class="status failed">Package server is not listening on ${escapeHTML(status.listen)}.</span>`;$('ps4ContentStatus').innerHTML=status.configured?`${listener} PS4 download URL: <strong>${escapeHTML(status.advertise_url)}</strong>`:`${listener}<br><span class="status failed">${escapeHTML(status.configuration_error||'PS3MGR_PS4_ADVERTISE_URL is not configured.')} Browsing works, but installs cannot start.</span>`;renderPS4Games()}catch(error){$('ps4GameGrid').innerHTML=`<div class="empty">${escapeHTML(error.message)}</div>`;toast(error.message,'error')}}
async function loadPS4CoverStatus(){const el=$('ps4CoverStatus');try{const status=await api('/api/ps4/covers/status'),path=escapeHTML(status.cache_dir||'covers/');if(status.error){el.innerHTML=`<strong>PS4 cover cache unavailable:</strong> <code>${path}</code><br><span class="status failed">${escapeHTML(status.error)}</span>`;return}el.innerHTML=`<strong>Local PS4 covers ready:</strong> <code>${path}</code> inside the container · ${status.images||0} cached image${status.images===1?'':'s'}. Embedded PKG icons are extracted once; manual CUSA images are reused first.`}catch(error){el.innerHTML=`<strong>PS4 cover status failed:</strong> <span class="status failed">${escapeHTML(error.message)}</span>`}}
function displayedPS4Games(){const q=state.ps4Search.toLowerCase();return state.ps4Games.filter(pkg=>{const matches=!q||pkg.title.toLowerCase().includes(q)||(pkg.title_id||'').toLowerCase().includes(q)||(pkg.content_id||'').toLowerCase().includes(q);if(!matches)return false;if(state.ps4Filter==='installed')return pkg.installed;if(state.ps4Filter==='missing')return !pkg.installed;if(state.ps4Filter==='queued')return state.ps4Queue.some(j=>j.package.id===pkg.id&&!['COMPLETED','FAILED','CANCELLED'].includes(j.state));return true}).sort((a,b)=>state.ps4Sort==='size'?b.size-a.size:a.title.localeCompare(b.title))}
function ps4QueueState(pkg){const item=[...state.ps4Queue].reverse().find(j=>j.package.id===pkg.id);if(item)return item.state==='WAITING'?'QUEUED':item.state;return pkg.installed?'INSTALLED':'NOT_INSTALLED'}
function renderPS4Games(){const list=displayedPS4Games();$('ps4GameGrid').classList.toggle('empty',!list.length);$('ps4GameGrid').innerHTML=list.length?list.map(pkg=>{const selected=state.ps4Selected.has(pkg.id),status=ps4QueueState(pkg),parts=asArray(pkg.parts);return`<article class="game-card ps4-game-card ${selected?'selected':''}" role="button" tabindex="0" aria-pressed="${selected}" aria-label="${attr(`${selected?'Deselect':'Select'} ${pkg.title}`)}" data-game="${attr(pkg.id)}"><div class="cover">${pkg.cover_url?`<img loading="lazy" src="${attr(pkg.cover_url)}" alt="">`:`<span class="placeholder">PS4</span>`}</div><div class="game-body"><h3 class="game-title" title="${attr(pkg.title)}">${escapeHTML(pkg.title)}</h3><div class="game-meta"><span>${escapeHTML(pkg.title_id||'CUSA unknown')}</span><span>${formatBytes(pkg.size)}</span></div><div class="game-meta"><span>${escapeHTML(pkg.format||'pkg')}</span><span>${parts.length} part${parts.length===1?'':'s'}</span></div><span class="status ${status.toLowerCase()}">${labelState(status)}</span></div></article>`}).join(''):'No PS4 packages match this view.';bindGameCards('.ps4-game-card',state.ps4Selected,renderPS4Games);renderPS4Selection()}
function renderPS4Selection(){let size=0;state.ps4Games.forEach(pkg=>{if(state.ps4Selected.has(pkg.id))size+=pkg.size});$('ps4SelectionCount').textContent=`${state.ps4Selected.size} package${state.ps4Selected.size===1?'':'s'} selected`;$('ps4SelectionSize').textContent=formatBytes(size);$('ps4InstallSelected').disabled=!state.ps4Selected.size||!state.ps4Console}
$('ps4GameSearch').oninput=e=>{state.ps4Search=e.target.value;renderPS4Games()};$('ps4GameFilter').onchange=e=>{state.ps4Filter=e.target.value;renderPS4Games()};$('ps4GameSort').onchange=e=>{state.ps4Sort=e.target.value;renderPS4Games()};$('ps4SelectAll').onclick=()=>{displayedPS4Games().forEach(pkg=>state.ps4Selected.add(pkg.id));renderPS4Games()};$('ps4SelectMissing').onclick=()=>{state.ps4Selected.clear();state.ps4Games.filter(pkg=>!pkg.installed).forEach(pkg=>state.ps4Selected.add(pkg.id));renderPS4Games()};$('ps4SelectNone').onclick=()=>{state.ps4Selected.clear();renderPS4Games()};
$('ps4InstallSelected').onclick=async()=>{try{const count=state.ps4Selected.size;await api('/api/ps4/queue',{method:'POST',body:JSON.stringify({console_id:state.ps4Console,package_ids:[...state.ps4Selected]})});state.ps4Selected.clear();await loadPS4Queue();renderPS4Games();toast(`${count} PS4 packages added to the PS4 queue`,'success');showView('ps4queue')}catch(error){toast(error.message,'error')}};
async function loadPS4Consoles(){try{state.ps4Consoles=asArray(await api('/api/ps4/consoles'));$('statPS4Consoles').textContent=state.ps4Consoles.length;renderPS4Consoles()}catch(error){toast(error.message,'error')}}
function renderPS4Consoles(){const el=$('ps4ConsoleGrid');el.classList.toggle('empty',!state.ps4Consoles.length);el.innerHTML=state.ps4Consoles.length?state.ps4Consoles.map(c=>`<article class="console-card ${state.ps4Console===c.id?'selected':''}"><p class="eyebrow">PLAYSTATION 4 / RPI</p><h3>${escapeHTML(c.ip)}:${c.api_port||12800}</h3><p><span class="online">● Remote Package Installer online</span></p><div class="console-actions"><button class="button ${state.ps4Console===c.id?'ghost':'primary'} select-ps4-console" data-id="${attr(c.id)}">${state.ps4Console===c.id?'Selected':'Select console'}</button><button class="button ghost refresh-ps4-console" data-id="${attr(c.id)}">↻ Check packages</button></div></article>`).join(''):'No PS4 consoles discovered yet.';document.querySelectorAll('.select-ps4-console').forEach(button=>button.onclick=()=>selectPS4Console(button.dataset.id));document.querySelectorAll('.refresh-ps4-console').forEach(button=>button.onclick=()=>refreshPS4Console(button.dataset.id,button))}
async function selectPS4Console(id){state.ps4Console=id;renderPS4Consoles();renderPS4Selection();toast(`Checking installed titles on ${id}:${state.ps4RPIPort}…`);try{state.ps4Games=asArray(await api(`/api/ps4/compare/${encodeURIComponent(id)}`));$('statPS4Installed').textContent=state.ps4Games.filter(pkg=>pkg.installed).length;renderPS4Games();toast(`${id}:${state.ps4RPIPort} selected`,'success');showView('ps4games')}catch(error){toast(error.message,'error')}}
async function refreshPS4Console(id,button){const original=button?.textContent;if(button){button.disabled=true;button.textContent='Checking…'}try{const result=await api(`/api/ps4/consoles/${encodeURIComponent(id)}/rescan`,{method:'POST'});await loadPS4Consoles();if(state.ps4Console===id){state.ps4Games=asArray(result.games);$('statPS4Installed').textContent=state.ps4Games.filter(pkg=>pkg.installed).length;renderPS4Games()}toast(`${id}:12800 package status refreshed`,'success')}catch(error){toast(error.message,'error')}finally{if(button){button.disabled=false;button.textContent=original}}}
$('ps4DirectForm').onsubmit=async event=>{event.preventDefault();const button=$('ps4DirectButton');button.disabled=true;button.textContent='Connecting…';try{const console=await api('/api/ps4/consoles',{method:'POST',body:JSON.stringify({ip:$('ps4DirectIP').value})});await loadPS4Consoles();toast(`${console.ip}:12800 added`,'success');await selectPS4Console(console.id)}catch(error){toast(error.message,'error')}finally{button.disabled=false;button.textContent='Add PS4 by IP'}};
$('ps4ScanForm').onsubmit=async event=>{event.preventDefault();const button=$('ps4ScanButton');button.disabled=true;button.textContent='Scanning…';$('ps4ScanResult').textContent='Checking port 12800 and verifying the Remote Package Installer API…';try{const found=asArray(await api('/api/ps4/scan',{method:'POST',body:JSON.stringify({cidr:$('ps4CIDR').value})}));await loadPS4Consoles();$('ps4ScanResult').textContent=found.length?`Found ${found.length} PS4 console${found.length===1?'':'s'}.`:'No PS4 Remote Package Installer found on port 12800.';if(found.length===1)await selectPS4Console(found[0].id)}catch(error){$('ps4ScanResult').textContent=error.message;toast(error.message,'error')}finally{button.disabled=false;button.textContent='Scan for PS4'}};
async function loadPS4Queue(){try{state.ps4Queue=asArray(await api('/api/ps4/queue'));renderPS4Queue();renderPS4Games()}catch(error){toast(error.message,'error')}}
function renderPS4Queue(){
  const active=state.ps4Queue.filter(job=>!['COMPLETED','FAILED','CANCELLED'].includes(job.state));
  $('ps4QueueBadge').textContent=active.length;
  $('statPS4Queue').textContent=active.length;
  const list=$('ps4QueueList');
  list.classList.toggle('empty',!state.ps4Queue.length);
  list.innerHTML=state.ps4Queue.length?state.ps4Queue.slice().reverse().map(item=>{
    const canCancel=['WAITING','VALIDATING','SERVING','REQUESTING_INSTALL','DOWNLOADING','VERIFYING'].includes(item.state);
    const canRetry=['FAILED','CANCELLED'].includes(item.state);
    const error=item.error?`<p class="status failed">${escapeHTML(item.error)}</p>`:'';
    return `<article class="queue-item"><div class="queue-top"><div><p class="eyebrow">${labelState(item.state)} · PS4 RPI :${state.ps4RPIPort}</p><h3>${escapeHTML(item.package.title)}</h3></div><strong>${(item.percentage||0).toFixed(1)}%</strong></div><div class="progress"><i style="width:${Math.min(100,item.percentage||0)}%"></i></div><div class="queue-details"><span>${formatBytes(item.bytes_transferred)} / ${formatBytes(item.total_bytes)}</span><span>${formatBytes(item.speed)}/s · ETA ${formatTime(item.eta_seconds)}</span><span>${escapeHTML(item.current_file||item.package.title_id||item.state)}</span></div>${error}<div class="queue-actions">${canCancel?`<button class="button ghost ps4-queue-action" data-action="cancel" data-id="${attr(item.id)}">Cancel</button>`:''}${canRetry?`<button class="button ghost ps4-queue-action" data-action="retry" data-id="${attr(item.id)}">Retry</button>`:''}</div></article>`;
  }).join(''):'The PS4 queue is empty.';
  document.querySelectorAll('.ps4-queue-action').forEach(button=>{
    button.onclick=async()=>{
      try{
        await api(`/api/ps4/queue/${encodeURIComponent(button.dataset.id)}/${button.dataset.action}`,{method:'POST'});
        await loadPS4Queue();
      }catch(error){toast(error.message,'error')}
    };
  });
}
$('pausePS4Queue').onclick=()=>api('/api/ps4/queue/pause',{method:'POST'}).then(()=>toast('PS4 queue paused after the active package')).catch(error=>toast(error.message,'error'));$('resumePS4Queue').onclick=()=>api('/api/ps4/queue/resume',{method:'POST'}).then(()=>toast('PS4 queue resumed','success')).catch(error=>toast(error.message,'error'));$('clearPS4Queue').onclick=()=>api('/api/ps4/queue/completed',{method:'DELETE'}).then(loadPS4Queue).catch(error=>toast(error.message,'error'));
async function loadPS5Games(){try{state.ps5Games=asArray(await api('/api/ps5/games'));$('statPS5Games').textContent=state.ps5Games.length;renderPS5Games()}catch(error){$('ps5GameGrid').innerHTML=`<div class="empty">${escapeHTML(error.message)}</div>`;toast(error.message,'error')}}
function displayedPS5Games(){const q=state.ps5Search.toLowerCase();return state.ps5Games.filter(g=>{const matches=!q||g.title.toLowerCase().includes(q)||(g.id||'').toLowerCase().includes(q);if(!matches)return false;if(state.ps5Filter==='installed')return g.installed;if(state.ps5Filter==='missing')return !g.installed;if(state.ps5Filter==='queued')return state.ps5Queue.some(t=>publicID(t.game)===publicID(g)&&!['COMPLETED','FAILED','CANCELLED'].includes(t.state));return true}).sort((a,b)=>state.ps5Sort==='size'?b.size-a.size:a.title.localeCompare(b.title))}
function ps5QueueState(game){const item=[...state.ps5Queue].reverse().find(t=>publicID(t.game)===publicID(game));if(item)return item.state==='WAITING'?'QUEUED':item.state;return game.installed?'INSTALLED':'NOT_INSTALLED'}
function renderPS5Games(){const list=displayedPS5Games();$('ps5GameGrid').classList.toggle('empty',!list.length);$('ps5GameGrid').innerHTML=list.length?list.map(game=>{const id=publicID(game),selected=state.ps5Selected.has(id),status=ps5QueueState(game);return`<article class="game-card ps5-game-card ${selected?'selected':''}" role="button" tabindex="0" aria-pressed="${selected}" aria-label="${attr(`${selected?'Deselect':'Select'} ${game.title}`)}" data-game="${attr(id)}"><div class="cover">${game.icon_url?`<img loading="lazy" src="${attr(game.icon_url)}" alt="">`:`<span class="placeholder">PS5</span>`}</div><div class="game-body"><h3 class="game-title" title="${attr(game.title)}">${escapeHTML(game.title)}</h3><div class="game-meta"><span>${escapeHTML(game.id||'ID unknown')}</span><span>${formatBytes(game.size)}</span></div><div class="game-meta"><span>${escapeHTML(game.format||'folder')}</span><span>FTP :2121</span></div><span class="status ${status.toLowerCase()}">${labelState(status)}</span></div></article>`}).join(''):'No PS5 games match this view.';bindGameCards('.ps5-game-card',state.ps5Selected,renderPS5Games);renderPS5Selection()}
function renderPS5Selection(){let size=0;state.ps5Games.forEach(g=>{if(state.ps5Selected.has(publicID(g)))size+=g.size});$('ps5SelectionCount').textContent=`${state.ps5Selected.size} game${state.ps5Selected.size===1?'':'s'} selected`;$('ps5SelectionSize').textContent=formatBytes(size);$('ps5InstallSelected').disabled=!state.ps5Selected.size||!state.ps5Console}
$('ps5GameSearch').oninput=e=>{state.ps5Search=e.target.value;renderPS5Games()};$('ps5GameFilter').onchange=e=>{state.ps5Filter=e.target.value;renderPS5Games()};$('ps5GameSort').onchange=e=>{state.ps5Sort=e.target.value;renderPS5Games()};$('ps5SelectAll').onclick=()=>{displayedPS5Games().forEach(g=>state.ps5Selected.add(publicID(g)));renderPS5Games()};$('ps5SelectMissing').onclick=()=>{state.ps5Selected.clear();state.ps5Games.filter(g=>!g.installed).forEach(g=>state.ps5Selected.add(publicID(g)));renderPS5Games()};$('ps5SelectNone').onclick=()=>{state.ps5Selected.clear();renderPS5Games()};
$('ps5InstallSelected').onclick=async()=>{try{const count=state.ps5Selected.size;await api('/api/ps5/queue',{method:'POST',body:JSON.stringify({console_id:state.ps5Console,game_ids:[...state.ps5Selected]})});state.ps5Selected.clear();await loadPS5Queue();renderPS5Games();toast(`${count} PS5 games queued for /data/etaHEN/games`,'success');showView('ps5queue')}catch(error){toast(error.message,'error')}};
async function loadPS5Consoles(){try{state.ps5Consoles=asArray(await api('/api/ps5/consoles'));$('statPS5Consoles').textContent=state.ps5Consoles.length;renderPS5Consoles()}catch(error){toast(error.message,'error')}}
function renderPS5Consoles(){const el=$('ps5ConsoleGrid');el.classList.toggle('empty',!state.ps5Consoles.length);el.innerHTML=state.ps5Consoles.length?state.ps5Consoles.map(c=>`<article class="console-card ${state.ps5Console===c.id?'selected':''}"><p class="eyebrow">PLAYSTATION 5 / ETAHEN</p><h3>${escapeHTML(c.ip)}:${c.ftp_port||2121}</h3><p><span class="online">● FTP online</span> · ${c.game_count} games in ShadowMountPlus</p><div class="console-actions"><button class="button ${state.ps5Console===c.id?'ghost':'primary'} select-ps5-console" data-id="${attr(c.id)}">${state.ps5Console===c.id?'Selected':'Select console'}</button><button class="button ghost refresh-ps5-console" data-id="${attr(c.id)}">↻ Refresh games</button><button class="button ghost installed-ps5-console" data-id="${attr(c.id)}">View installed</button></div></article>`).join(''):'No PS5 consoles discovered yet.';document.querySelectorAll('.select-ps5-console').forEach(button=>button.onclick=()=>selectPS5Console(button.dataset.id));document.querySelectorAll('.refresh-ps5-console').forEach(button=>button.onclick=()=>refreshPS5Console(button.dataset.id,button));document.querySelectorAll('.installed-ps5-console').forEach(button=>button.onclick=()=>showInstalledGames('ps5',button.dataset.id))}
async function selectPS5Console(id){state.ps5Console=id;renderPS5Consoles();renderPS5Selection();toast(`Loading ShadowMountPlus games from ${id}:2121…`);try{state.ps5Games=asArray(await api(`/api/ps5/compare/${encodeURIComponent(id)}`));$('statPS5Installed').textContent=state.ps5Games.filter(g=>g.installed).length;renderPS5Games();toast(`${id}:2121 selected`,'success');showView('ps5games')}catch(error){toast(error.message,'error')}}
async function refreshPS5Console(id,button){const original=button?.textContent;if(button){button.disabled=true;button.textContent='Refreshing…'}try{const result=await api(`/api/ps5/consoles/${encodeURIComponent(id)}/rescan`,{method:'POST'});await loadPS5Consoles();if(state.ps5Console===id){state.ps5Games=asArray(result.games);$('statPS5Installed').textContent=state.ps5Games.filter(g=>g.installed).length;renderPS5Games()}toast(`${id}:2121 refreshed — ${result.console.game_count} games found`,'success')}catch(error){toast(error.message,'error')}finally{if(button){button.disabled=false;button.textContent=original}}}
$('ps5DirectForm').onsubmit=async event=>{event.preventDefault();const button=$('ps5DirectButton');button.disabled=true;button.textContent='Connecting…';try{const console=await api('/api/ps5/consoles',{method:'POST',body:JSON.stringify({ip:$('ps5DirectIP').value})});await loadPS5Consoles();toast(`${console.ip}:2121 added`,'success');await selectPS5Console(console.id)}catch(error){toast(error.message,'error')}finally{button.disabled=false;button.textContent='Add PS5 by IP'}};
$('ps5ScanForm').onsubmit=async event=>{event.preventDefault();const button=$('ps5ScanButton');button.disabled=true;button.textContent='Scanning…';$('ps5ScanResult').textContent='Checking port 2121 and etaHEN filesystem markers…';try{const found=asArray(await api('/api/ps5/scan',{method:'POST',body:JSON.stringify({cidr:$('ps5CIDR').value})}));await loadPS5Consoles();$('ps5ScanResult').textContent=found.length?`Found ${found.length} PS5 console${found.length===1?'':'s'}.`:'No etaHEN PS5 found on port 2121.';if(found.length===1)await selectPS5Console(found[0].id)}catch(error){$('ps5ScanResult').textContent=error.message;toast(error.message,'error')}finally{button.disabled=false;button.textContent='Scan for PS5'}};
async function loadPS5Queue(){try{state.ps5Queue=asArray(await api('/api/ps5/queue'));renderPS5Queue();renderPS5Games()}catch(error){toast(error.message,'error')}}
function renderPS5Queue(){const active=state.ps5Queue.filter(q=>!['COMPLETED','FAILED','CANCELLED'].includes(q.state));$('ps5QueueBadge').textContent=active.length;$('statPS5Queue').textContent=active.length;const list=$('ps5QueueList');list.classList.toggle('empty',!state.ps5Queue.length);list.innerHTML=state.ps5Queue.length?state.ps5Queue.slice().reverse().map(item=>`<article class="queue-item"><div class="queue-top"><div><p class="eyebrow">${labelState(item.state)} · PS5 FTP :2121</p><h3>${escapeHTML(item.game.title)}</h3></div><strong>${(item.percentage||0).toFixed(1)}%</strong></div><div class="progress"><i style="width:${Math.min(100,item.percentage||0)}%"></i></div><div class="queue-details"><span>${formatBytes(item.bytes_transferred)} / ${formatBytes(item.total_bytes)}</span><span>${formatBytes(item.speed)}/s · ETA ${formatTime(item.eta_seconds)}</span><span>${escapeHTML(item.current_file||'/data/etaHEN/games')}</span></div>${item.error?`<p class="status failed">${escapeHTML(item.error)}</p>`:''}<div class="queue-actions">${['WAITING','STARTING','TRANSFERRING','VERIFYING'].includes(item.state)?`<button class="button ghost ps5-queue-action" data-action="cancel" data-id="${attr(item.id)}">Cancel</button>`:''}${['FAILED','CANCELLED'].includes(item.state)?`<button class="button ghost ps5-queue-action" data-action="retry" data-id="${attr(item.id)}">Retry</button>`:''}</div></article>`).join(''):'The PS5 queue is empty.';document.querySelectorAll('.ps5-queue-action').forEach(b=>b.onclick=async()=>{try{await api(`/api/ps5/queue/${encodeURIComponent(b.dataset.id)}/${b.dataset.action}`,{method:'POST'});await loadPS5Queue()}catch(error){toast(error.message,'error')}})}
$('pausePS5Queue').onclick=()=>api('/api/ps5/queue/pause',{method:'POST'}).then(()=>toast('PS5 queue paused after the active game')).catch(e=>toast(e.message,'error'));$('resumePS5Queue').onclick=()=>api('/api/ps5/queue/resume',{method:'POST'}).then(()=>toast('PS5 queue resumed','success')).catch(e=>toast(e.message,'error'));$('clearPS5Queue').onclick=()=>api('/api/ps5/queue/completed',{method:'DELETE'}).then(loadPS5Queue).catch(e=>toast(e.message,'error'));
function connectEvents(){const source=new EventSource('/api/events');source.onopen=()=>{$('eventStatus').textContent='Live updates connected'};source.onerror=()=>{$('eventStatus').textContent='Reconnecting live updates…'};['queue.progress','queue.item_started','queue.item_completed','queue.item_failed','queue.item_cancelled','queue.completed'].forEach(type=>source.addEventListener(type,event=>{const envelope=JSON.parse(event.data),item=envelope.payload;if(type==='queue.item_completed'){toast(`✓ ${item.game.title} installed`,'success');notify(`${item.game.title} installed`)}if(type==='queue.item_failed'){toast(`${item.game.title} failed: ${item.error}`,'error');notify(`${item.game.title} failed`)}if(type==='queue.completed')toast('Installation queue completed','success');loadQueue()}));['scan.host_found','console.connected','games.updated'].forEach(type=>source.addEventListener(type,()=>loadConsoles()));
['ps2.job.started','ps2.conversion.progress','ps2.write.progress','ps2.job.completed','ps2.job.failed','ps2.job.paused','ps2.job.cancelled','ps2.queue.completed'].forEach(type=>source.addEventListener(type,event=>{const envelope=JSON.parse(event.data),item=envelope.payload;if(type==='ps2.job.completed'){toast(`✓ ${item.game.title} installed to ${item.usb_id}`,'success');notify(`${item.game.title} installed to ${item.usb_id}`)}if(type==='ps2.job.failed')toast(`${item.game.title} failed: ${item.error}`,'error');if(type==='ps2.job.paused')toast(`USB disconnected. PS2 queue paused for ${item.usb_id}`,'error');if(type==='ps2.queue.completed')toast(`PS2 queue completed: ${item.completed} installed, ${item.failed} failed`,item.failed?'error':'success');loadPS2Queue()}));['ps2.usb.connected','ps2.usb.disconnected','ps2.usb.prepared'].forEach(type=>source.addEventListener(type,()=>loadUSB()));['ps2.covers.cached','ps2.covers.failed'].forEach(type=>source.addEventListener(type,()=>loadPS2CoverStatus()));['ps4.covers.cached','ps4.covers.failed'].forEach(type=>source.addEventListener(type,()=>loadPS4CoverStatus()));['ps4.job.started','ps4.pkg.serving','ps4.install.requested','ps4.download.progress','ps4.job.completed','ps4.job.failed','ps4.job.cancelled','ps4.queue.completed'].forEach(type=>source.addEventListener(type,event=>{const envelope=JSON.parse(event.data),item=envelope.payload;if(type==='ps4.job.completed'){toast(`✓ ${item.package.title} installed on PS4`,'success');notify(`${item.package.title} installed on PS4`)}if(type==='ps4.job.failed')toast(`${item.package.title} failed: ${item.error}`,'error');if(type==='ps4.queue.completed')toast(`PS4 queue completed: ${item.completed} installed, ${item.failed} failed`,item.failed?'error':'success');loadPS4Queue()}));['ps4.scan.host_found','ps4.console.connected'].forEach(type=>source.addEventListener(type,()=>loadPS4Consoles()));['ps5.queue.progress','ps5.queue.item_started','ps5.queue.item_completed','ps5.queue.item_failed','ps5.queue.item_cancelled','ps5.queue.completed'].forEach(type=>source.addEventListener(type,event=>{const envelope=JSON.parse(event.data),item=envelope.payload;if(type==='ps5.queue.item_completed'){toast(`✓ ${item.game.title} copied to ShadowMountPlus`,'success');notify(`${item.game.title} installed on PS5`)}if(type==='ps5.queue.item_failed')toast(`${item.game.title} failed: ${item.error}`,'error');if(type==='ps5.queue.completed')toast('PS5 queue completed','success');loadPS5Queue()}));['ps5.scan.host_found','ps5.console.connected'].forEach(type=>source.addEventListener(type,()=>loadPS5Consoles()))}
$('notifyBtn').onclick=async()=>{if(!('Notification'in window))return toast('Browser notifications are unavailable','error');const permission=await Notification.requestPermission();toast(permission==='granted'?'Notifications enabled':'Notifications were not enabled',permission==='granted'?'success':'')};
function notify(body){if('Notification'in window&&Notification.permission==='granted')new Notification('PlayStation Manager',{body})}
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function attr(value){return escapeHTML(value)}
Promise.all([loadPS2Games(),loadPS2CoverStatus(),loadUSB(),loadPS2Queue(),loadGames(),loadConsoles(),loadQueue(),loadPS4Games(),loadPS4CoverStatus(),loadPS4Consoles(),loadPS4Queue(),loadPS5Games(),loadPS5Consoles(),loadPS5Queue()]).catch(()=>{});connectEvents();
