const state={games:[],consoles:[],queue:[],selected:new Set(),console:null,filter:'all',search:'',sort:'title'};
const $=id=>document.getElementById(id);
const api=async(url,options={})=>{const response=await fetch(url,{headers:{'Content-Type':'application/json'},...options});if(!response.ok){let body={};try{body=await response.json()}catch{}throw new Error(body.error||`Request failed (${response.status})`)}return response.status===204?null:response.json()};
const formatBytes=n=>{if(!n)return'0 B';const units=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return`${n.toFixed(i<2?0:1)} ${units[i]}`};
const formatTime=s=>{if(!s)return'—';const m=Math.floor(s/60);return m?`${m}m ${s%60}s`:`${s}s`};
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('.nav').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$('pageTitle').textContent={dashboard:'Dashboard',games:'Game Library',consoles:'PS3 Consoles',scan:'Network Scan',queue:'Transfer Queue'}[name];$('eyebrow').textContent={dashboard:'LIBRARY OVERVIEW',games:'LOCAL COLLECTION',consoles:'CONNECTED HARDWARE',scan:'DISCOVERY',queue:'INSTALLATION ACTIVITY'}[name]}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));
function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('toasts').append(el);setTimeout(()=>el.remove(),4500)}
async function loadGames(){try{state.games=await api('/api/local-games');$('statGames').textContent=state.games.length;renderGames()}catch(error){$('gameGrid').innerHTML=`<div class="empty">${escapeHTML(error.message)}</div>`;toast(error.message,'error')}}
function displayedGames(){let games=state.games.filter(g=>{const q=state.search.toLowerCase();const matches=!q||g.title.toLowerCase().includes(q)||(g.id||'').toLowerCase().includes(q);if(!matches)return false;if(state.filter==='installed')return g.installed;if(state.filter==='missing')return !g.installed;if(state.filter==='queued')return state.queue.some(t=>t.game.id===g.id&&!['COMPLETED','FAILED','CANCELLED'].includes(t.state));return true});return games.sort((a,b)=>state.sort==='size'?b.size-a.size:a.title.localeCompare(b.title))}
function renderGames(){const list=displayedGames();$('gameGrid').classList.toggle('empty',!list.length);$('gameGrid').innerHTML=list.length?list.map(game=>{const id=publicID(game),selected=state.selected.has(id),status=queueState(game);return`<article class="game-card ${selected?'selected':''}"><input class="game-check" type="checkbox" data-game="${attr(id)}" ${selected?'checked':''}><div class="cover">${game.icon_url?`<img loading="lazy" src="${attr(game.icon_url)}" alt="">`:`<span class="placeholder">PS3</span>`}</div><div class="game-body"><h3 class="game-title" title="${attr(game.title)}">${escapeHTML(game.title)}</h3><div class="game-meta"><span>${escapeHTML(game.id||'ID unknown')}</span><span>${formatBytes(game.size)}</span></div><span class="status ${status.toLowerCase()}">${labelState(status)}</span></div></article>`}).join(''):'No games match this view.';document.querySelectorAll('.game-check').forEach(box=>box.addEventListener('change',()=>{box.checked?state.selected.add(box.dataset.game):state.selected.delete(box.dataset.game);renderGames();renderSelection()}));renderSelection()}
function publicID(game){return game.id||game.title.toLowerCase().replace(/[^a-z0-9]/g,'')}
function queueState(game){const item=[...state.queue].reverse().find(t=>publicID(t.game)===publicID(game));if(item)return item.state==='WAITING'?'QUEUED':item.state;return game.installed?'INSTALLED':'NOT_INSTALLED'}
function labelState(value){return({NOT_INSTALLED:'+ NOT INSTALLED',INSTALLED:'✓ INSTALLED',QUEUED:'◷ QUEUED',WAITING:'◷ WAITING',STARTING:'→ STARTING',TRANSFERRING:'↥ TRANSFERRING',VERIFYING:'◇ VERIFYING',COMPLETED:'✓ COMPLETED',FAILED:'! FAILED',CANCELLED:'× CANCELLED'})[value]||value}
function renderSelection(){let size=0;state.games.forEach(g=>{if(state.selected.has(publicID(g)))size+=g.size});$('selectionCount').textContent=`${state.selected.size} game${state.selected.size===1?'':'s'} selected`;$('selectionSize').textContent=formatBytes(size);$('installSelected').disabled=!state.selected.size||!state.console}
$('gameSearch').addEventListener('input',e=>{state.search=e.target.value;renderGames()});$('gameFilter').addEventListener('change',e=>{state.filter=e.target.value;renderGames()});$('gameSort').addEventListener('change',e=>{state.sort=e.target.value;renderGames()});
$('selectAll').onclick=()=>{displayedGames().forEach(g=>state.selected.add(publicID(g)));renderGames()};$('selectMissing').onclick=()=>{state.selected.clear();state.games.filter(g=>!g.installed).forEach(g=>state.selected.add(publicID(g)));renderGames()};$('selectNone').onclick=()=>{state.selected.clear();renderGames()};
$('installSelected').onclick=async()=>{try{await api('/api/queue',{method:'POST',body:JSON.stringify({console_id:state.console,game_ids:[...state.selected]})});toast(`${state.selected.size} games added to the queue`,'success');state.selected.clear();await loadQueue();renderGames();showView('queue')}catch(error){toast(error.message,'error')}};
async function loadConsoles(){state.consoles=await api('/api/consoles');$('statConsoles').textContent=state.consoles.length;renderConsoles()}
function renderConsoles(){const el=$('consoleGrid');el.classList.toggle('empty',!state.consoles.length);el.innerHTML=state.consoles.length?state.consoles.map(c=>`<article class="console-card ${state.console===c.id?'selected':''}"><p class="eyebrow">PLAYSTATION 3</p><h3>${escapeHTML(c.ip)}</h3><p><span class="online">● FTP online</span> · ${c.game_count} games found</p><div class="console-actions"><button class="button ${state.console===c.id?'ghost':'primary'} select-console" data-id="${attr(c.id)}">${state.console===c.id?'Selected':'Select console'}</button><button class="button ghost refresh-console" data-id="${attr(c.id)}">↻ Refresh games</button></div></article>`).join(''):'No consoles discovered yet.';document.querySelectorAll('.select-console').forEach(button=>button.onclick=()=>selectConsole(button.dataset.id));document.querySelectorAll('.refresh-console').forEach(button=>button.onclick=()=>refreshConsole(button.dataset.id,button))}
async function selectConsole(id){state.console=id;renderConsoles();toast(`Loading games from ${id}…`);try{state.games=await api(`/api/compare/${encodeURIComponent(id)}`);$('statInstalled').textContent=state.games.filter(g=>g.installed).length;renderGames();renderSelection();toast(`${id} selected`,'success');showView('games')}catch(error){toast(error.message,'error')}}
async function refreshConsole(id,button){const original=button?.textContent;if(button){button.disabled=true;button.textContent='Refreshing…'}try{const result=await api(`/api/consoles/${encodeURIComponent(id)}/rescan`,{method:'POST'});await loadConsoles();if(state.console===id){state.games=result.games;$('statInstalled').textContent=state.games.filter(g=>g.installed).length;renderGames();renderSelection()}toast(`${id} refreshed — ${result.console.game_count} games found`,'success')}catch(error){toast(error.message,'error')}finally{if(button){button.disabled=false;button.textContent=original}}}
$('directForm').onsubmit=async event=>{event.preventDefault();const button=$('directButton');button.disabled=true;button.textContent='Connecting…';try{const console=await api('/api/consoles',{method:'POST',body:JSON.stringify({ip:$('directIP').value})});await loadConsoles();toast(`${console.ip} added`,'success');await selectConsole(console.id)}catch(error){toast(error.message,'error')}finally{button.disabled=false;button.textContent='Add PS3 by IP'}};
$('scanForm').onsubmit=async event=>{event.preventDefault();const button=$('scanButton');button.disabled=true;button.textContent='Scanning…';$('scanResult').textContent='Checking FTP endpoints and PS3 filesystem markers…';try{const found=await api('/api/scan',{method:'POST',body:JSON.stringify({cidr:$('cidr').value})});await loadConsoles();$('scanResult').textContent=found.length?`Found ${found.length} PS3 console${found.length===1?'':'s'}.`:'No PS3 console found in that network.';if(found.length===1)await selectConsole(found[0].id)}catch(error){$('scanResult').textContent=error.message;toast(error.message,'error')}finally{button.disabled=false;button.textContent='Scan network'}};
async function loadQueue(){try{state.queue=await api('/api/queue');renderQueue();renderGames()}catch(error){toast(error.message,'error')}}
function renderQueue(){const active=state.queue.filter(q=>!['COMPLETED','FAILED','CANCELLED'].includes(q.state));$('queueBadge').textContent=active.length;$('statQueue').textContent=active.length;const list=$('queueList');list.classList.toggle('empty',!state.queue.length);list.innerHTML=state.queue.length?state.queue.slice().reverse().map(item=>`<article class="queue-item"><div class="queue-top"><div><p class="eyebrow">${labelState(item.state)}</p><h3>${escapeHTML(item.game.title)}</h3></div><strong>${(item.percentage||0).toFixed(1)}%</strong></div><div class="progress"><i style="width:${Math.min(100,item.percentage||0)}%"></i></div><div class="queue-details"><span>${formatBytes(item.bytes_transferred)} / ${formatBytes(item.total_bytes)}</span><span>${formatBytes(item.speed)}/s · ETA ${formatTime(item.eta_seconds)}</span><span>${escapeHTML(item.current_file||'Waiting')}</span></div>${item.error?`<p class="status failed">${escapeHTML(item.error)}</p>`:''}<div class="queue-actions">${['WAITING','STARTING','TRANSFERRING','VERIFYING'].includes(item.state)?`<button class="button ghost queue-action" data-action="cancel" data-id="${attr(item.id)}">Cancel</button>`:''}${['FAILED','CANCELLED'].includes(item.state)?`<button class="button ghost queue-action" data-action="retry" data-id="${attr(item.id)}">Retry</button>`:''}</div></article>`).join(''):'Your queue is empty.';$('recentQueue').innerHTML=state.queue.length?state.queue.slice(-4).reverse().map(q=>`<div class="queue-details"><strong>${escapeHTML(q.game.title)}</strong><span class="status ${q.state.toLowerCase()}">${labelState(q.state)}</span></div>`).join(''):'No transfers yet. Choose games to begin.';document.querySelectorAll('.queue-action').forEach(b=>b.onclick=async()=>{try{await api(`/api/queue/${encodeURIComponent(b.dataset.id)}/${b.dataset.action}`,{method:'POST'});await loadQueue()}catch(error){toast(error.message,'error')}})}
$('pauseQueue').onclick=()=>api('/api/queue/pause',{method:'POST'}).then(()=>toast('Queue paused after the active game')).catch(e=>toast(e.message,'error'));
$('resumeQueue').onclick=()=>api('/api/queue/resume',{method:'POST'}).then(()=>toast('Queue resumed','success')).catch(e=>toast(e.message,'error'));
$('clearQueue').onclick=()=>api('/api/queue/completed',{method:'DELETE'}).then(loadQueue).catch(e=>toast(e.message,'error'));
function connectEvents(){const source=new EventSource('/api/events');source.onopen=()=>{$('eventStatus').textContent='Live updates connected'};source.onerror=()=>{$('eventStatus').textContent='Reconnecting live updates…'};['queue.progress','queue.item_started','queue.item_completed','queue.item_failed','queue.item_cancelled','queue.completed'].forEach(type=>source.addEventListener(type,event=>{const envelope=JSON.parse(event.data),item=envelope.payload;if(type==='queue.item_completed'){toast(`✓ ${item.game.title} installed`,'success');notify(`${item.game.title} installed`)}if(type==='queue.item_failed'){toast(`${item.game.title} failed: ${item.error}`,'error');notify(`${item.game.title} failed`)}if(type==='queue.completed')toast('Installation queue completed','success');loadQueue()}));['scan.host_found','console.connected','games.updated'].forEach(type=>source.addEventListener(type,()=>loadConsoles()))}
$('notifyBtn').onclick=async()=>{if(!('Notification'in window))return toast('Browser notifications are unavailable','error');const permission=await Notification.requestPermission();toast(permission==='granted'?'Notifications enabled':'Notifications were not enabled',permission==='granted'?'success':'')};
function notify(body){if('Notification'in window&&Notification.permission==='granted')new Notification('PS3 Game Manager',{body})}
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function attr(value){return escapeHTML(value)}
Promise.all([loadGames(),loadConsoles(),loadQueue()]).catch(()=>{});connectEvents();
